### ISSUE TITLE
[프론트엔드] <커리큘럼 - 케틀FIT> 만들기

### ISSUE THREAD

**Issue by kongjingyu** [ButFit/ButFitSeoulWeb#8]

**Comment by kongjingyu** [comment]
- 디자인 안은 추후 전달 예정

**Comment by kongjingyu** [comment]
해당 페이지 최상단 영역의 배경이 되는 이미지 파일입니다.

![default](https://user-images.githubusercontent.com/10165523/52543031-4fbe1d00-2de9-11e9-8f47-09211462f0fd.png)

**Comment by kongjingyu** [comment]
이건 지원서 2번째 페이지 filter 에 보면 특정 커리큘럼 자세히 보기 버튼 눌렀을 때 나타나는 팝업 이미지 입니다.

![- fit](https://user-images.githubusercontent.com/10165523/52543558-f73d4e80-2ded-11e9-9b22-ff575101bff6.png)

**Comment by kongjingyu** [comment]
상단 우측 <img_slider>에 들어갈 이미지 3장 입니다.
![_1](https://user-images.githubusercontent.com/10165523/52545905-83577200-2dfe-11e9-9b3d-24c66d567777.jpeg)
![_2](https://user-images.githubusercontent.com/10165523/52545906-83577200-2dfe-11e9-9248-dc57ff5ca508.jpeg)
![_3](https://user-images.githubusercontent.com/10165523/52545907-83f00880-2dfe-11e9-8c95-0fb62d2733bf.jpeg)

**Comment by kongjingyu** [comment]
3줄을 2줄로 줄이기 위한 문구 수정

<맨몸>
맨몸 운동과 셀프 마사지로 FIT BODY 만들기

<바>
맨몸 운동과 셀프 마사지로 FIT BODY 만들기
<케틀>

<웨이필라>

**Comment by wonook** [comment]
> 상단 우측 <img_slider>에 들어갈 이미지 3장 입니다.
> ![_1](https://user-images.githubusercontent.com/10165523/52545905-83577200-2dfe-11e9-9b3d-24c66d567777.jpeg)
> ![_2](https://user-images.githubusercontent.com/10165523/52545906-83577200-2dfe-11e9-9248-dc57ff5ca508.jpeg)
> ![_3](https://user-images.githubusercontent.com/10165523/52545907-83f00880-2dfe-11e9-8c95-0fb62d2733bf.jpeg)

이거 jpg로 주셔야 할 것 같아요

**Comment by wonook** [comment]
> 해당 페이지 최상단 영역의 배경이 되는 이미지 파일입니다.
> 
> ![default](https://user-images.githubusercontent.com/10165523/52543031-4fbe1d00-2de9-11e9-8f47-09211462f0fd.png)

요것두 jpg
